name: Auto deploy to github/cloudfare pages

on:
  push:
    branches: [ "main" ]
    paths-ignore: 
      - '**/README.md'
      # - '**/*.yml'
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0,3,13 * * *'  # 每6h一次
  workflow_dispatch:  # 触发手动事件


permissions:
  contents: write

jobs:
  chromego-mergo:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python/chromego_merge
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v2

    - name: Use Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Update Git Submodule
      run: |
        cd .. && cd ..
        git submodule init
        git submodule update --remote
    
    - name: Install dependencies
      run: |
        pwd
        ls -la
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run merge script
      run: |
        python meta_merge.py 

    - name: Run shadowrocket merge script
      run: |
        python merge.py

    - uses: actions/upload-artifact@v3
      with:
        name: hexo-fluid-blog
        path: /home/runner/work/hexo-fluid-blog/hexo-fluid-blog


  chromego:
    if: ${{ success() }}
    needs: chromego-mergo
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - name: Use Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - uses: actions/download-artifact@v3
      with:
        name: hexo-fluid-blog
        path: ./
    
    - name: Install dependencies
      run: |
        pwd
        ls -la
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: create ChromeGo Config markdown post
      run: |
        pwd
        rm -rf downlaod
        mkdir -p downlaod
        sudo apt-get install wget curl axel p7zip-full -y
        cd downlaod
        axel -n 10 --output=ChromeGo.7z https://github.com/bannedbook/fanqiang/releases/download/ChromeGo-latest/ChromeGo.7z
        7z x ChromeGo.7z
        ls -la ChromeGo
        cd ..
        python get_chromego_config.py

    - name: create VPN markdown post
      run: |
        pwd
        python main.py
        cat source/_posts/VPN合集.md

    - uses: actions/upload-artifact@v3
      with:
        name: hexo-fluid-blog
        path: ./


  auto-publish:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: chromego
    defaults:
      run:
        working-directory: ./
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - uses: actions/download-artifact@v3
      with:
        name: hexo-fluid-blog
        path: ./

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc
    
    - name: Setup Git
      env:
        ACTION_KEY: ${{ secrets.ACTION_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$ACTION_KEY" > ~/.ssh/id_rsa
        chmod 700 ~/.ssh
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config user.email "actions@github.com"
        git config user.name "GitHub Action"
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Action"

    - name: Install Node Modules
      run: |
        rm -f .yarnclean yarn.lock
        yarn global add hexo-cli
        yarn --non-interactive --silent
        yarn list --depth=0

    - name: Auto Publish to Github Pages
      run: |
        rm -rf ./public
        yarn run hexo clean
        yarn run hexo generate
        yarn run hexo deploy
    
    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: fluid-blog
        directory: ./public
        # Optional: Enable this if you want to have GitHub Deployments triggered
        gitHubToken: ${{ secrets.ACTION_TOKEN }}
        # Optional: Switch what branch you are publishing to.
        # By default this will be the branch which triggered this workflow
        branch: main
        # Optional: Change the working directory
        # All my website content is in the site folder
        workingDirectory: .
        # Optional: Change the Wrangler version, allows you to point to a specific version or a tag such as `beta`
        wranglerVersion: '3'

    - name: Auto Commit Changes
      run: |
        git status
        git branch -a
        cat .git/config
        git add .
        git commit --allow-empty -m "github actions auto updated at $(date '+%Y-%m-%d %H:%M:%S')"
        git push

