name: ChromeGo Merge Script

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0,3,13 * * *'  # 每6h一次
  workflow_dispatch:  # 触发手动事件

# on:  
#   # push:
#   #   tags:
#   #     - 'v*'
#   schedule:
#     - cron: '0 0,3,13 * * *'  # 每6h一次
#   workflow_dispatch:  # 触发手动事件

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Setup Git
        env:
          ACTION_KEY: ${{ secrets.ACTION_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
      
      - name: Update Submodule
        run: |
          git submodule init
          git submodule update --remote

      - name: Install dependencies
        run: |
          cd python/chromego_merge
          pip install -r requirements.txt

      - name: Run merge script
        run: |
          cd python/chromego_merge  
          python meta_merge.py 

      - name: Run shadowrocket merge script
        run: |
          cd python/chromego_merge
          python merge.py
      
      - name: create VPN markdown file
        run: |
          pwd
          python main.py
          cat source/_posts/VPN合集.md
      
      - name: Commit Changes
        run: |
          git status
          git branch -a
          cat .git/config
          git add .
          git commit --allow-empty -m "pdated at $(date '+%Y-%m-%d %H:%M:%S')"
          git push
